language: python
cache: pip
python:
  - "3.5"
  - "3.6" # 3.5 development branch

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
services:
  - redis-server
env:
  global: 
    - REDIS_HOST_TEST=localhost
    - REDIS_PORT_TEST=6379
