language: python
cache: pip
services:
  - docker
python:
  - "3.6"

# command to install dependencies
install:
  - "docker-compose run --rm web /code/ve/bin/python -m unittest"
# command to run tests
script: nosetests
