language: python
cache: pip
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
# command to run tests
script: nosetests
