version: '3.5'

services:

  dynamodb:
    image: instructure/dynamo-local-admin
    restart: always
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - dynamodata:/var/lib/dynamo

volumes:
  dynamodata:
    driver: local
