version: '3.5'

services:
  web:
    restart: always
    build: .
    expose:
      - "8001"
    ports:
      - 8001:8001

    links:
      - dynamodb:dynamodb
    depends_on:
      - dynamodb
    volumes:
      - .:/code/docb
    env_file: .env

  dynamodb:
    image: instructure/dynamo-local-admin
    restart: always
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - dynamodata:/var/lib/dynamo

volumes:
  dynamodata:
    driver: local
